### ISSUE TITLE
Switch to css modules

### ISSUE THREAD

**Issue by nik-55** [mdgspace/activity-leaderboard#76]
Css modules allow us to scope css files. It will help in avoid clashing in css names and the style of one css file is not applied to other without our knowledge. Refer [here](https://www.gatsbyjs.com/docs/how-to/styling/css-modules/#:~:text=A%20CSS%20Module%20is%20a,for%20additional%20processing%20and%20safety.).

**Comment by kituuu** [comment]
Hey @nik-55 , I am interested in this issue, can you assign this to me?
